<img src="/assets/container_add.ico" alt="asset" class="preload" />
<img src="/assets/container.ico" alt="asset" class="preload" />
<img src="/assets/folder_add.ico" alt="asset" class="preload" />
<img src="/assets/folder.ico" alt="asset" class="preload" />
<img src="/assets/logo_small.png" alt="asset" class="preload" />
<img src="/assets/logo.png" alt="asset" class="preload" />
<img src="/assets/prefab.ico" alt="asset" class="preload" />
<img src="/assets/scene_add.ico" alt="asset" class="preload" />
<img src="/assets/scene.ico" alt="asset" class="preload" />
<img src="/assets/sprite_add.ico" alt="asset" class="preload" />
<img src="/assets/sprite.ico" alt="asset" class="preload" />
<img src="/assets/texture.ico" alt="asset" class="preload" />
