export const Icons = {
    Select: '/assets/select.ico',
    Transform: '/assets/transform.ico',
    Scene: '/assets/scene.ico',
    SceneAdd: '/assets/scene_add.ico',
    Folder: '/assets/folder.ico',
    FolderAdd: '/assets/folder_add.ico',
    PrefabAsset: '/assets/prefab-asset.ico',
    PrefabAssetVariant: '/assets/prefab-asset-variant.ico',
    PrefabInstanceReference: '/assets/prefab-instance-reference.ico',
    PrefabInstanceVariant: '/assets/prefab-instance-variant.ico',
    Sprite: '/assets/sprite.ico',
    SpriteAdd: '/assets/sprite_add.ico',
    TextureAsset: '/assets/texture.ico',
    Container: '/assets/container.ico',
    ContainerAdd: '/assets/container_add.ico',
} as const;
